# Site settings
title: Polar Finch
description: Electronic Music Producer
url: http://127.0.0.1:4000
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Polar Finch'
  email: polarfinchmusic@gmail.com
  spotify_username: https://open.spotify.com/artist/6kR7TOgSftpLyonF2iISxm?si=q92chQG9Q2iT2W-rkCG94Q
  instagram_username: "polarfinch_"
  facebook_username: polarfinchmusic
  # github_username:  joshgerdes
  # linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - screenshot.png
  - "Music/Music/Media.localized/Music/Nicolas Jaar"
  - Music
 